version: '3.9'

services:
  # Zookeeper para Kafka
  zookeeper:
    image: bitnami/zookeeper:3.8
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  # Kafka
  kafka:
    image: bitnami/kafka:3.4.0
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper

  # LocalStack
  localstack:
    image: localstack/localstack:2.2
    container_name: localstack
    ports:
      - "4566:4566"
      - "4571:4571"
    environment:
      - SERVICES=dynamodb
      - DEFAULT_REGION=sa-east-1
      - DATA_DIR=/tmp/localstack/data
    volumes:
      - "./localstack:/tmp/localstack"

  # Init DynamoDB Tables
  init-dynamodb:
    image: amazon/aws-cli
    depends_on:
      - localstack
    environment:
      - AWS_ACCESS_KEY_ID=dummy
      - AWS_SECRET_ACCESS_KEY=dummy
      - AWS_DEFAULT_REGION=sa-east-1
    entrypoint:
      - /bin/sh
      - -c
      - |
        echo "Criando tabelas no LocalStack DynamoDB..."

        # Tabela outbox_events com GSI
        aws --endpoint-url=http://localstack:4566 --region sa-east-1 dynamodb create-table \
          --table-name outbox_events \
          --attribute-definitions \
              AttributeName=messageId,AttributeType=S \
              AttributeName=createdAt,AttributeType=S \
              AttributeName=status,AttributeType=S \
          --key-schema \
              AttributeName=messageId,KeyType=HASH \
              AttributeName=createdAt,KeyType=RANGE \
          --billing-mode PAY_PER_REQUEST \
          --global-secondary-indexes '[
            {
              "IndexName": "status-index",
              "KeySchema":[{"AttributeName":"status","KeyType":"HASH"},{"AttributeName":"createdAt","KeyType":"RANGE"}],
              "Projection":{"ProjectionType":"ALL"},
              "ProvisionedThroughput":{"ReadCapacityUnits":5,"WriteCapacityUnits":5}
            }
          ]'

        # Tabela processed_messages
        aws --endpoint-url=http://localstack:4566 --region sa-east-1 dynamodb create-table \
          --table-name processed_messages \
          --attribute-definitions AttributeName=messageId,AttributeType=S \
          --key-schema AttributeName=messageId,KeyType=HASH \
          --billing-mode PAY_PER_REQUEST

        echo "Tabelas criadas com sucesso!"